trigger: none


variables:
- group: Infra_IAC_Var
pool:
  name: 'AgentPool1'

stages:


  - stage: Terraform_Destroy
    displayName: 'Terraform Destroy'
    jobs:
      - job: terraform_destroy
        displayName: 'Destroy Infrastructure using Terraform'
        steps:
          - task: AzureCLI@2
            displayName: 'Login to Azure'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal -u '$(client_id)' -p '$(client_secret)' --tenant '$(tenant_id)'
            
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: '$(Build.SourcesDirectory)/infrastructure'
              inlineScript: |
                export ARM_CLIENT_ID="$(client_id)"             
                export ARM_CLIENT_SECRET="$(client_secret)"     
                export ARM_TENANT_ID="$(tenant_id)"            
                export ARM_SUBSCRIPTION_ID="$(subscription_id)"
                echo "💥 Destroying Terraform-managed Infrastructure..."
                terraform init -reconfigure
                terraform destroy -auto-approve -var-file=$(tfvarsFile)
